# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import habitaciones_pb2 as habitaciones__pb2
except ImportError:
    import habitaciones_pb2 as habitaciones__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in habitaciones_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HabitacionesServiceStub:
    """==========================================
    Servicio de Habitaciones (gRPC Interno)
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearHabitacion = channel.unary_unary(
                '/hotel.habitaciones.v1.HabitacionesService/CrearHabitacion',
                request_serializer=habitaciones__pb2.CrearHabitacionRequest.SerializeToString,
                response_deserializer=habitaciones__pb2.CrearHabitacionResponse.FromString,
                _registered_method=True)
        self.ListarHabitaciones = channel.unary_unary(
                '/hotel.habitaciones.v1.HabitacionesService/ListarHabitaciones',
                request_serializer=habitaciones__pb2.ListarHabitacionesRequest.SerializeToString,
                response_deserializer=habitaciones__pb2.ListarHabitacionesResponse.FromString,
                _registered_method=True)
        self.ConsultarDisponibilidad = channel.unary_unary(
                '/hotel.habitaciones.v1.HabitacionesService/ConsultarDisponibilidad',
                request_serializer=habitaciones__pb2.ConsultarDisponibilidadRequest.SerializeToString,
                response_deserializer=habitaciones__pb2.ConsultarDisponibilidadResponse.FromString,
                _registered_method=True)
        self.ListarDisponibilidad = channel.unary_unary(
                '/hotel.habitaciones.v1.HabitacionesService/ListarDisponibilidad',
                request_serializer=habitaciones__pb2.ListarDisponibilidadRequest.SerializeToString,
                response_deserializer=habitaciones__pb2.ListarDisponibilidadResponse.FromString,
                _registered_method=True)
        self.AsignarHabitacion = channel.unary_unary(
                '/hotel.habitaciones.v1.HabitacionesService/AsignarHabitacion',
                request_serializer=habitaciones__pb2.AsignarHabitacionRequest.SerializeToString,
                response_deserializer=habitaciones__pb2.AsignarHabitacionResponse.FromString,
                _registered_method=True)
        self.LiberarHabitacion = channel.unary_unary(
                '/hotel.habitaciones.v1.HabitacionesService/LiberarHabitacion',
                request_serializer=habitaciones__pb2.LiberarHabitacionRequest.SerializeToString,
                response_deserializer=habitaciones__pb2.LiberarHabitacionResponse.FromString,
                _registered_method=True)
        self.ConsultarAsignacion = channel.unary_unary(
                '/hotel.habitaciones.v1.HabitacionesService/ConsultarAsignacion',
                request_serializer=habitaciones__pb2.ConsultarAsignacionRequest.SerializeToString,
                response_deserializer=habitaciones__pb2.ConsultarAsignacionResponse.FromString,
                _registered_method=True)


class HabitacionesServiceServicer:
    """==========================================
    Servicio de Habitaciones (gRPC Interno)
    ==========================================
    """

    def CrearHabitacion(self, request, context):
        """Gestión de Catálogo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarHabitaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarDisponibilidad(self, request, context):
        """Consultas de Disponibilidad
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarDisponibilidad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsignarHabitacion(self, request, context):
        """Operaciones de Reserva (Idempotentes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiberarHabitacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarAsignacion(self, request, context):
        """Verificación para resiliencia ante fallos de red (T7)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HabitacionesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearHabitacion': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearHabitacion,
                    request_deserializer=habitaciones__pb2.CrearHabitacionRequest.FromString,
                    response_serializer=habitaciones__pb2.CrearHabitacionResponse.SerializeToString,
            ),
            'ListarHabitaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarHabitaciones,
                    request_deserializer=habitaciones__pb2.ListarHabitacionesRequest.FromString,
                    response_serializer=habitaciones__pb2.ListarHabitacionesResponse.SerializeToString,
            ),
            'ConsultarDisponibilidad': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarDisponibilidad,
                    request_deserializer=habitaciones__pb2.ConsultarDisponibilidadRequest.FromString,
                    response_serializer=habitaciones__pb2.ConsultarDisponibilidadResponse.SerializeToString,
            ),
            'ListarDisponibilidad': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarDisponibilidad,
                    request_deserializer=habitaciones__pb2.ListarDisponibilidadRequest.FromString,
                    response_serializer=habitaciones__pb2.ListarDisponibilidadResponse.SerializeToString,
            ),
            'AsignarHabitacion': grpc.unary_unary_rpc_method_handler(
                    servicer.AsignarHabitacion,
                    request_deserializer=habitaciones__pb2.AsignarHabitacionRequest.FromString,
                    response_serializer=habitaciones__pb2.AsignarHabitacionResponse.SerializeToString,
            ),
            'LiberarHabitacion': grpc.unary_unary_rpc_method_handler(
                    servicer.LiberarHabitacion,
                    request_deserializer=habitaciones__pb2.LiberarHabitacionRequest.FromString,
                    response_serializer=habitaciones__pb2.LiberarHabitacionResponse.SerializeToString,
            ),
            'ConsultarAsignacion': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarAsignacion,
                    request_deserializer=habitaciones__pb2.ConsultarAsignacionRequest.FromString,
                    response_serializer=habitaciones__pb2.ConsultarAsignacionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel.habitaciones.v1.HabitacionesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotel.habitaciones.v1.HabitacionesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HabitacionesService:
    """==========================================
    Servicio de Habitaciones (gRPC Interno)
    ==========================================
    """

    @staticmethod
    def CrearHabitacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.habitaciones.v1.HabitacionesService/CrearHabitacion',
            habitaciones__pb2.CrearHabitacionRequest.SerializeToString,
            habitaciones__pb2.CrearHabitacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarHabitaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.habitaciones.v1.HabitacionesService/ListarHabitaciones',
            habitaciones__pb2.ListarHabitacionesRequest.SerializeToString,
            habitaciones__pb2.ListarHabitacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarDisponibilidad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.habitaciones.v1.HabitacionesService/ConsultarDisponibilidad',
            habitaciones__pb2.ConsultarDisponibilidadRequest.SerializeToString,
            habitaciones__pb2.ConsultarDisponibilidadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarDisponibilidad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.habitaciones.v1.HabitacionesService/ListarDisponibilidad',
            habitaciones__pb2.ListarDisponibilidadRequest.SerializeToString,
            habitaciones__pb2.ListarDisponibilidadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsignarHabitacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.habitaciones.v1.HabitacionesService/AsignarHabitacion',
            habitaciones__pb2.AsignarHabitacionRequest.SerializeToString,
            habitaciones__pb2.AsignarHabitacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiberarHabitacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.habitaciones.v1.HabitacionesService/LiberarHabitacion',
            habitaciones__pb2.LiberarHabitacionRequest.SerializeToString,
            habitaciones__pb2.LiberarHabitacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarAsignacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.habitaciones.v1.HabitacionesService/ConsultarAsignacion',
            habitaciones__pb2.ConsultarAsignacionRequest.SerializeToString,
            habitaciones__pb2.ConsultarAsignacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
